//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobRegPro.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MobRegPro.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DemoLicenseActivated {
            get {
                return ResourceManager.GetString("DemoLicenseActivated", resourceCulture);
            }
        }
        
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        public static string btnAbout {
            get {
                return ResourceManager.GetString("btnAbout", resourceCulture);
            }
        }
        
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        public static string btnActivate {
            get {
                return ResourceManager.GetString("btnActivate", resourceCulture);
            }
        }
        
        public static string lbProgress {
            get {
                return ResourceManager.GetString("lbProgress", resourceCulture);
            }
        }
        
        public static string tbName {
            get {
                return ResourceManager.GetString("tbName", resourceCulture);
            }
        }
        
        public static string tbMail {
            get {
                return ResourceManager.GetString("tbMail", resourceCulture);
            }
        }
        
        public static string padViewPrompt {
            get {
                return ResourceManager.GetString("padViewPrompt", resourceCulture);
            }
        }
        
        public static string padViewClear {
            get {
                return ResourceManager.GetString("padViewClear", resourceCulture);
            }
        }
        
        public static string itemSummary {
            get {
                return ResourceManager.GetString("itemSummary", resourceCulture);
            }
        }
        
        public static string SignatureTooLong {
            get {
                return ResourceManager.GetString("SignatureTooLong", resourceCulture);
            }
        }
        
        public static string cpSettings {
            get {
                return ResourceManager.GetString("cpSettings", resourceCulture);
            }
        }
        
        public static string tbsTitle {
            get {
                return ResourceManager.GetString("tbsTitle", resourceCulture);
            }
        }
        
        public static string swDefaultInUse {
            get {
                return ResourceManager.GetString("swDefaultInUse", resourceCulture);
            }
        }
        
        public static string tbDefaultUsername {
            get {
                return ResourceManager.GetString("tbDefaultUsername", resourceCulture);
            }
        }
        
        public static string tbDefaultCarID {
            get {
                return ResourceManager.GetString("tbDefaultCarID", resourceCulture);
            }
        }
        
        public static string tbDefaultPassword {
            get {
                return ResourceManager.GetString("tbDefaultPassword", resourceCulture);
            }
        }
        
        public static string cpResources {
            get {
                return ResourceManager.GetString("cpResources", resourceCulture);
            }
        }
        
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        public static string lblCaption {
            get {
                return ResourceManager.GetString("lblCaption", resourceCulture);
            }
        }
        
        public static string enCaption {
            get {
                return ResourceManager.GetString("enCaption", resourceCulture);
            }
        }
        
        public static string lblPriority {
            get {
                return ResourceManager.GetString("lblPriority", resourceCulture);
            }
        }
        
        public static string enPriority {
            get {
                return ResourceManager.GetString("enPriority", resourceCulture);
            }
        }
        
        public static string lblOnReport {
            get {
                return ResourceManager.GetString("lblOnReport", resourceCulture);
            }
        }
        
        public static string lblPicture {
            get {
                return ResourceManager.GetString("lblPicture", resourceCulture);
            }
        }
        
        public static string lblRegistration {
            get {
                return ResourceManager.GetString("lblRegistration", resourceCulture);
            }
        }
        
        public static string itemAdd {
            get {
                return ResourceManager.GetString("itemAdd", resourceCulture);
            }
        }
        
        public static string CaptionIsEmpty {
            get {
                return ResourceManager.GetString("CaptionIsEmpty", resourceCulture);
            }
        }
        
        public static string lblgOnReport {
            get {
                return ResourceManager.GetString("lblgOnReport", resourceCulture);
            }
        }
        
        public static string lblgIsReadOnly {
            get {
                return ResourceManager.GetString("lblgIsReadOnly", resourceCulture);
            }
        }
        
        public static string lblgPriority {
            get {
                return ResourceManager.GetString("lblgPriority", resourceCulture);
            }
        }
        
        public static string lblgDate {
            get {
                return ResourceManager.GetString("lblgDate", resourceCulture);
            }
        }
        
        public static string lblgRegistration {
            get {
                return ResourceManager.GetString("lblgRegistration", resourceCulture);
            }
        }
        
        public static string btnInput {
            get {
                return ResourceManager.GetString("btnInput", resourceCulture);
            }
        }
        
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        public static string btnTakePicture {
            get {
                return ResourceManager.GetString("btnTakePicture", resourceCulture);
            }
        }
        
        public static string piInput {
            get {
                return ResourceManager.GetString("piInput", resourceCulture);
            }
        }
        
        public static string NoCameraTitle {
            get {
                return ResourceManager.GetString("NoCameraTitle", resourceCulture);
            }
        }
        
        public static string NoCameraText {
            get {
                return ResourceManager.GetString("NoCameraText", resourceCulture);
            }
        }
        
        public static string CameraFailed {
            get {
                return ResourceManager.GetString("CameraFailed", resourceCulture);
            }
        }
        
        public static string cpPlanningList {
            get {
                return ResourceManager.GetString("cpPlanningList", resourceCulture);
            }
        }
        
        public static string itemRefresh {
            get {
                return ResourceManager.GetString("itemRefresh", resourceCulture);
            }
        }
        
        public static string lblProgressRegistrations {
            get {
                return ResourceManager.GetString("lblProgressRegistrations", resourceCulture);
            }
        }
        
        public static string lblProgressPlanning {
            get {
                return ResourceManager.GetString("lblProgressPlanning", resourceCulture);
            }
        }
        
        public static string btnStatusChange {
            get {
                return ResourceManager.GetString("btnStatusChange", resourceCulture);
            }
        }
        
        public static string btnRegistrations {
            get {
                return ResourceManager.GetString("btnRegistrations", resourceCulture);
            }
        }
        
        public static string btnInfo {
            get {
                return ResourceManager.GetString("btnInfo", resourceCulture);
            }
        }
        
        public static string btnArticles {
            get {
                return ResourceManager.GetString("btnArticles", resourceCulture);
            }
        }
        
        public static string btnResources {
            get {
                return ResourceManager.GetString("btnResources", resourceCulture);
            }
        }
        
        public static string lbStatus {
            get {
                return ResourceManager.GetString("lbStatus", resourceCulture);
            }
        }
        
        public static string tbUserName {
            get {
                return ResourceManager.GetString("tbUserName", resourceCulture);
            }
        }
        
        public static string tbCar {
            get {
                return ResourceManager.GetString("tbCar", resourceCulture);
            }
        }
        
        public static string tbPassword {
            get {
                return ResourceManager.GetString("tbPassword", resourceCulture);
            }
        }
        
        public static string btnLoginGo {
            get {
                return ResourceManager.GetString("btnLoginGo", resourceCulture);
            }
        }
        
        public static string cpLogin {
            get {
                return ResourceManager.GetString("cpLogin", resourceCulture);
            }
        }
        
        public static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }
        
        public static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        public static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        public static string OrderInfo {
            get {
                return ResourceManager.GetString("OrderInfo", resourceCulture);
            }
        }
        
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        public static string Technician {
            get {
                return ResourceManager.GetString("Technician", resourceCulture);
            }
        }
        
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        public static string StopTime {
            get {
                return ResourceManager.GetString("StopTime", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        public static string CustomerInfo {
            get {
                return ResourceManager.GetString("CustomerInfo", resourceCulture);
            }
        }
        
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        public static string PhoneNr {
            get {
                return ResourceManager.GetString("PhoneNr", resourceCulture);
            }
        }
        
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        public static string HouseNr {
            get {
                return ResourceManager.GetString("HouseNr", resourceCulture);
            }
        }
        
        public static string Zipcode {
            get {
                return ResourceManager.GetString("Zipcode", resourceCulture);
            }
        }
        
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string Technicians {
            get {
                return ResourceManager.GetString("Technicians", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        public static string InGroup {
            get {
                return ResourceManager.GetString("InGroup", resourceCulture);
            }
        }
        
        public static string InstallationReport {
            get {
                return ResourceManager.GetString("InstallationReport", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        public static string Pauze {
            get {
                return ResourceManager.GetString("Pauze", resourceCulture);
            }
        }
        
        public static string TechCount {
            get {
                return ResourceManager.GetString("TechCount", resourceCulture);
            }
        }
        
        public static string RegistrationInfo {
            get {
                return ResourceManager.GetString("RegistrationInfo", resourceCulture);
            }
        }
        
        public static string ReadInstructionsFirst {
            get {
                return ResourceManager.GetString("ReadInstructionsFirst", resourceCulture);
            }
        }
        
        public static string ArticleUsage {
            get {
                return ResourceManager.GetString("ArticleUsage", resourceCulture);
            }
        }
        
        public static string ArticleNr {
            get {
                return ResourceManager.GetString("ArticleNr", resourceCulture);
            }
        }
        
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        public static string tbArticleID {
            get {
                return ResourceManager.GetString("tbArticleID", resourceCulture);
            }
        }
        
        public static string btnScan {
            get {
                return ResourceManager.GetString("btnScan", resourceCulture);
            }
        }
        
        public static string tbQty {
            get {
                return ResourceManager.GetString("tbQty", resourceCulture);
            }
        }
        
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        public static string itemSearch {
            get {
                return ResourceManager.GetString("itemSearch", resourceCulture);
            }
        }
        
        public static string ScanBarcode {
            get {
                return ResourceManager.GetString("ScanBarcode", resourceCulture);
            }
        }
        
        public static string EnterValidArticleNr {
            get {
                return ResourceManager.GetString("EnterValidArticleNr", resourceCulture);
            }
        }
        
        public static string EnterValidQty {
            get {
                return ResourceManager.GetString("EnterValidQty", resourceCulture);
            }
        }
        
        public static string DeleteArticle {
            get {
                return ResourceManager.GetString("DeleteArticle", resourceCulture);
            }
        }
        
        public static string cpArticle {
            get {
                return ResourceManager.GetString("cpArticle", resourceCulture);
            }
        }
        
        public static string cpArtGroup {
            get {
                return ResourceManager.GetString("cpArtGroup", resourceCulture);
            }
        }
        
        public static string cpActivationPage {
            get {
                return ResourceManager.GetString("cpActivationPage", resourceCulture);
            }
        }
        
        public static string lblLicenseKey {
            get {
                return ResourceManager.GetString("lblLicenseKey", resourceCulture);
            }
        }
        
        public static string tbLicenseKey {
            get {
                return ResourceManager.GetString("tbLicenseKey", resourceCulture);
            }
        }
        
        public static string btnActiveLicense {
            get {
                return ResourceManager.GetString("btnActiveLicense", resourceCulture);
            }
        }
        
        public static string btnMissing {
            get {
                return ResourceManager.GetString("btnMissing", resourceCulture);
            }
        }
        
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        public static string tbEmail {
            get {
                return ResourceManager.GetString("tbEmail", resourceCulture);
            }
        }
        
        public static string btnEmail {
            get {
                return ResourceManager.GetString("btnEmail", resourceCulture);
            }
        }
        
        public static string ScanLicenseCode {
            get {
                return ResourceManager.GetString("ScanLicenseCode", resourceCulture);
            }
        }
        
        public static string LicenseRequested {
            get {
                return ResourceManager.GetString("LicenseRequested", resourceCulture);
            }
        }
        
        public static string cpAbout {
            get {
                return ResourceManager.GetString("cpAbout", resourceCulture);
            }
        }
        
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        public static string MissingSignature {
            get {
                return ResourceManager.GetString("MissingSignature", resourceCulture);
            }
        }
        
        public static string NotAllRequiredRegistrationsProcessed {
            get {
                return ResourceManager.GetString("NotAllRequiredRegistrationsProcessed", resourceCulture);
            }
        }
        
        public static string NextStatus {
            get {
                return ResourceManager.GetString("NextStatus", resourceCulture);
            }
        }
        
        public static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        public static string btnClearTables {
            get {
                return ResourceManager.GetString("btnClearTables", resourceCulture);
            }
        }
        
        public static string tbsData {
            get {
                return ResourceManager.GetString("tbsData", resourceCulture);
            }
        }
        
        public static string txtTablesCleared {
            get {
                return ResourceManager.GetString("txtTablesCleared", resourceCulture);
            }
        }
    }
}
